name: Feature Request
description: 提交功能建议
title: "[Feature] "
labels:
  - enhancement
body:
  - type: textarea
    id: scenario
    attributes:
      label: 业务场景
      description: 该需求服务哪个用户流程
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 方案描述
      description: 建议实现方式和关键交互
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: 验收标准
      description: 如何判断需求完成
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: 优先级建议
      options:
        - P0
        - P1
        - P2
    validations:
      required: true

